---
- name: install nginx
  become: yes
  become_user: root
  apt:  pkg=nginx state=latest

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx


