---
root_group: root
nginx_conf_path: /etc/nginx/conf.d
nginx_conf_file_path: /etc/nginx/nginx.conf
nginx_mime_file_path: /etc/nginx/mime.types
nginx_pidfile: /run/nginx.pid
nginx_vhost_path: /etc/nginx/sites-enabled
nginx_default_vhost_path: /etc/nginx/sites-enabled/default
__nginx_user: "www-data"          
remote_www_dir: "/var/www/symfony"
nginx_vhost_projectname: "symfony"
nginx_vhost_projectwebroot: "/var/www/symfony/web"
nginx_fastcgi_ipport: "127.0.0.1:9000"
nginx_fastcgi_index: "index.php"
nginx_vhost_location: '~ \.php$'
nginx_vhost_root:  "{{ nginx_vhost_projectwebroot }}"
nginx_vhost_access_log: "/var/log/nginx/{{ nginx_vhost_projectname }}_access.log"
nginx_vhost_error_log: "/var/log/nginx/{{ nginx_vhost_projectname }}_error.log"