---
- name: Create webservers with Nginx, PHP, Composer and Symfony
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - roles/webserver/vars/main.yml
  roles:
    - aws


- hosts: webserver
  become: yes 
  remote_user: ubuntu
  gather_facts: True
  roles:
    - webserver
    - elb