---
- name: Set php_executable variable to a default if not defined.
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: Check if Symfony is installed.
  stat: "path={{ symfony_path }}"
  register: symfony_bin

- name: Download Symfony installer.
  become: yes
  become_user: root
  command: curl -LsS https://symfony.com/installer -o "{{ symfony_path }}"
  when: not symfony_bin.stat.exists

- name: Make Symfony executable
  become: yes
  become_user: root
  file: path="{{ symfony_path }}" state=touch mode="u+rwx,a-rx"
  when: symfony_bin.stat.exists

- name: Add symfony_home_path bin directory to global $PATH.
  template:
    src: symfony.sh.j2
    dest: /etc/profile.d/symfony.sh
    mode: 0644
  when: symfony_add_to_path and not symfony_bin.stat.exists
