---
webroot: "/var/www/symfony/web"
web_dir: "/var/www/symfony"
web_ami_id: ami-21d30f42
web_ins_type: t2.micro
web_key_name: tradetracker-keypair
web_group_id: sg-362f3352
web_vpc_id: vpc-cc4a81a8
web_subnet_ida: subnet-63982015
web_subnet_idb: subnet-272fa643
web_region: ap-southeast-1
sys_packages:
  - mcrypt
  - vim
  - htop

# LB configuration

