---
symfony_webroot: "/var/www/symfony/web"
symfony_web_dir: "/var/www/symfony"
symfony_webroot_cache: "/var/www/symfony/app/cache"
symfony_webroot_logs: "/var/www/symfony/app/logs"
symfony_web_user: www-data
web_ami_id: ami-21d30f42
web_ins_type: t2.micro
web_key_name: tradetracker-keypair
web_group_id: sg-362f3352
web_vpc_id: vpc-cc4a81a8
web_subnet_ida: subnet-63982015
web_subnet_idb: subnet-272fa643
web_region: ap-southeast-1
ENV: testing
web_application: nginx-symfony
web_server_role: webserver
server_hosts: webserver
inventory_hosts: "/etc/ansible/inventory/hosts"
php_mongo_enable: true
php_version_enable: "5.6"
php_cli_enable: "/usr/bin/php{{ php_version_enable }} -c /etc/php/{{ php_version_enable }}/fpm/php.ini"
php_cli_fpm_ini_enable: true
php_cli_fpm_ini_path: "/etc/php/{{ php_version_enable }}/fpm/php.ini"
load_balancer_name: "{{ testing-webserver-ELB }}"
sys_packages:
  - mcrypt
  - vim
  - htop


