---
web_ami_id: ami-xxxxxx
web_ins_type: t2-micro
web_key_name: xxxxxxxxxx
web_group_id: sg-xxxxx
web_vpc_id: vpc-xxxxx
web_subnet_ida: subnet-xxxxx
web_subnet_idb: subnet-xxxxx
web_region: xxxxxxxx
ENV: testing
local_server_group: "[dbserver]"
web_application: postgres-cluster
web_server_role: dbserver
server_hosts: dbserver
inventory_hosts: "/etc/ansible/inventory/hosts"
# postgres configurations to be created
postgresql_repmgr_user: repmgr
postgresql_repmgr_user_pass: xxxxx
postgresql_repmgr_db: repmgr
postgresql_port: 5432
postgresql_project_user: xxxxxxx
postgresql_project_pass: 'xxxxxx'
postgresql_project_db: xxxxxxx
postgresql_service_name: "postgresql"
postgresql_bin_directory: /usr/bin
postgresql_systl_kernel_shmmax: 236857600
postgresql_master_server: 'xxxxxx'


# List of databases to be created
postgresql_databases:
  - name: '{{ postgresql_project_db }}'
    owner: '{{ postgresql_project_user }}'

postgresql_users:
  - name: '{{ postgresql_project_user }}'
    pass: '{{ postgresql_project_pass }}'
    encrypted: no       

# List of databases with extensions to be created
postgresql_database_extensions: []

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: '{{ postgresql_project_user }}'                   
    db: '{{ postgresql_project_db }}'                 
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags
    when: postgresql_project_user

postgresql_pg_hba_custom:
  - { type: host, database: all, user: all, address: '{{ ansible_eth1.ipv4.address }}/32', method: '{{ postgresql_default_auth_method }}', comment: 'Master Slave configuration' }
  - { type: host, database: repmgr, user: repmgr, address: '{{ ansible_eth1.ipv4.address }}/32', method: '{{ postgresql_default_auth_method }}', comment: 'repmgr configuration' }
  - { type: host, database: repmgr, user: replication, address: '{{ ansible_eth1.ipv4.address }}/32', method: '{{ postgresql_default_auth_method }}', comment: 'repmgr configuration' }


sys_packages:
  - mcrypt
  - vim
  - htop


