---
- name: Install MongoDB
  become: yes
  become_user: root
  apt:  pkg=mongodb state=latest

- name: Install MongoDB
  become: yes
  become_user: root
  apt:  pkg=python-pymongo state=latest

- name: Allow access to MongoDB from anywhere
  become: yes
  become_user: root
  lineinfile: dest=/etc/mongodb.conf regexp="^bind_ip" line="#bind_ip = 127.0.0.1"
  notify: restart mongodb

- name: Install mongo php driver
  become: yes
  become_user: root
  apt:  pkg=php-mongodb state=latest
  when: php_mongo_enable