---
- name: Create SSH keys for the user in question
  become: yes
  user: name='{{ ssh_user }}' generate_ssh_key=yes ssh_key_bits=2048

- name: Get the public key off the machine
  become: yes
  slurp:
    src: "~{{ ssh_user }}/.ssh/id_rsa.pub"
  register: sshkey

- name: Install key on remote hosts
  become: yes
  authorized_key: user={{ ssh_user }} key="{{ sshkey.content|b64decode }}"
  delegate_to: "{{ item }}"
  with_items: play_hosts

- name: Setup known hosts file
  become: yes
  template: src=known_hosts.j2 dest=/etc/ssh/ssh_known_hosts mode=0644 owner=root group=root


