---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
    follow: true
  with_flattened:
    - "{{ php_conf_paths }}"
    - "{{ php_extension_conf_paths }}"

- name: Place PHP configuration file in place.
  template:
    src: php.ini.j2
    dest: "{{ item }}/php.ini"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_conf_paths }}"
  notify: restart webserver
  when: php_use_managed_ini

- name: enable mongodb driver module.
  template:
    src: mongodb.ini.j2
    dest: "/etc/php/{{ php_version_enable }}/mods-available/mongodb.ini"
    owner: root
    group: root
    mode: 0644