---
- name: Clone git repository
  git: dest={{ web_dir }} repo=https://github.com/adildhar/symfony.git update=no
  become: yes
  register: cloned

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  become: yes
  args:
    creates: /usr/local/bin/composer

- name: copy local parameters file
  copy: src=parameters.yml dest={{ web_dir }}/app/config

- name: run composer for dependencies
  command: /usr/bin/php5.6 /usr/local/bin/composer install -d {{ web_dir }}
  ignore_errors: yes