---
- name:  PostgreSQL Slave configuration | Stop PostgreSQL Service
  become: yes
  service:
    name: "{{ postgresql_service_name }}"
    state: stopped

- name: PostgreSQl Slave Configuration | Check repmgr exists
  become: yes
  stat: path="/var/run/postgresql/replregistered"
  tags: replmgr
  register: statslv